application: bbstop10
version: 1
runtime: python
api_version: 1

default_expiration: '3650d'

skip_files: |
  ^(.*/)?(
  (app\.yaml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (cron\.yaml)|
  (cron\.yml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*\.po)|
  (.*\.pot)|
  (\..*)|
  (app\.yaml\.sample)|
  (index\.yaml\.sample)|
  (cron\.yaml\.sample)|
  (manage\.py)|
  (TODO)|
  (TODO\.pdf)|
  (README)|
  (README\.pdf)|
  (LICENSE)|
  (scripts\/.*)|
  (docs\/.*)|
  (kay\/management\/.*)|
  (kay\/tests\/.*)|
  )$


handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  secure: optional
  login: admin

- url: /media
  static_dir: _generated_media
  secure: optional

- url: /.*
  script: common/appenginepatch/main.py
  secure: optional
